name: Go

on:
  push:
    branches: [ master, development ]
  pull_request:
    branches: [ master, development ]

jobs:

  testing:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.16

      - name: Build
        run: go build -v ./...

      - name: Test
        env:
          token: ${{ secrets.TOKEN }}
        run: go test -v ./...

      - name: Lint
        uses: Jerome1337/golint-action@v1.0.2
        with:
          golint-path: './...'
